export const sample_foods: any[] = [
  {
    // id:'1',
    name: "Vegetables Pizza",
    price: 9,
    cookTime: "40-45",
    favorite: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "assets/icons/meatball.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    // id:'2',
    name: "Pizza Pepperoni",
    price: 9,
    cookTime: "15-25",
    favorite: false,
    origins: ["italy", "asian"],
    stars: 3.0,
    imageUrl: "assets/icons/Cheesy-Vegetable-Pizza.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    // id:'3',
    name: "SandWitch",
    price: 9,
    cookTime: "15-20",
    favorite: false,
    origins: ["italy", "american"],
    stars: 4.0,
    imageUrl: "assets/icons/meatball.jpg",
    tags: ["FastFood", "Lunch"],
  },
  {
    // id:'4',
    name: "Chicken Soup",
    price: 9,
    cookTime: "20-30",
    favorite: false,
    origins: ["Aus", "new", "Inida"],
    stars: 4.0,
    imageUrl: "assets/icons/Cheesy-Vegetable-Pizza.jpg",
    tags: ["FastFood", "Lunch"],
  },
  {
    // id:'5',
    name: "MeatBall",
    price: 9,
    cookTime: "10-20",
    favorite: false,
    origins: ["Inida"],
    stars: 4.0,
    imageUrl: "assets/icons/meatball.jpg",
    tags: ["FastFood", "Lunch"],
  },
  {
    // id:'6',
    name: "Chhole Bhature",
    price: 9,
    cookTime: "25-35",
    favorite: false,
    origins: ["Inida"],
    stars: 4.0,
    imageUrl: "assets/icons/Cheesy-Vegetable-Pizza.jpg",
    tags: ["FastFood", "Lunch"],
  },
];

export const sample_tags: any[] = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "SlowFood", count: 2 },
  { name: "Hamburger", count: 1 },
  { name: "Fry", count: 1 },
  { name: "Soup", count: 1 },
];

export const sample_users: any[] = [
  {
    // id:'2',
    name: "Pizza Pepperoni",
    price: 9,
    cookTime: "15-25",
    favorite: false,
    origins: ["italy", "asian"],
    stars: 3.0,
    imageUrl: "assets/icons/Cheesy-Vegetable-Pizza.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    name: "Jane Doe",
    email: "john@gmail.com",
    password: "123456",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "admin lol",
    email: "admin@gmail.com",
    password: "12345",
    address: "Sanghai",
    isAdmin: false,
  },
];

export const new_foods: any[] = [
  {
    name: "Pasta Carbonara",
    price: 12,
    cookTime: "20-30",
    favorite: true,
    origins: ["Italian"],
    stars: 4.2,
    imageUrl: "assets/icons/pasta.jpg",
    tags: ["Lunch", "Dinner"],
  },
  {
    name: "Chicken Tenders",
    price: 7,
    cookTime: "15-20",
    favorite: false,
    origins: ["American"],
    stars: 3.7,
    imageUrl: "assets/icons/chicken-tender.jpg",
    tags: ["FastFood", "Lunch"],
  },
  {
    name: "Steak Dinner",
    price: 18,
    cookTime: "25-35",
    favorite: true,
    origins: ["American"],
    stars: 4.9,
    imageUrl: "assets/icons/steak.jfif",
    tags: ["Dinner"],
  },

  {
    name: "Fish and Chips",
    price: 11,
    cookTime: "20-30",
    favorite: true,
    origins: ["British"],
    stars: 4.3,
    imageUrl: "assets/icons/fish-chip.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    // id:'5',
    name: "MeatBall",
    price: 9,
    cookTime: "10-20",
    favorite: false,
    origins: ["Inida"],
    stars: 4.0,
    imageUrl: "assets/icons/meatball.jpg",
    tags: ["FastFood", "Lunch"],
  },

  {
    name: "Pizza Pepperoni",
    price: 9,
    cookTime: "15-25",
    favorite: false,
    origins: ["Italy", "American"],
    stars: 4.0,
    imageUrl: "assets/icons/pizza.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    name: "Burger Deluxe",
    price: 8,
    cookTime: "10-20",
    favorite: true,
    origins: ["American"],
    stars: 4.5,
    imageUrl: "assets/icons/burger.png",
    tags: ["FastFood", "Lunch"],
  },
  {
    name: "Sushi Combo",
    price: 15,
    cookTime: "30-40",
    favorite: false,
    origins: ["Japanese"],
    stars: 4.8,
    imageUrl: "assets/icons/sushi.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },

  {
    name: "Feijoada",
    price: 14,
    cookTime: "30-40",
    favorite: false,
    origins: ["Brazil"],
    stars: 4.6,
    imageUrl: "assets/icons/feijoada.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },

  {
    name: "Dim Sum",
    price: 10,
    cookTime: "20-30",
    favorite: false,
    origins: ["China"],
    stars: 4.2,
    imageUrl: "assets/icons/dim-sum.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
];
